### ISSUE TITLE
[PE-D][Tester D] Incorrect Commands for `add` and `edit` in Command Summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-4/tp#135] opened 2024-04-05 21:13 UTC
As shown in the screenshot below, the commands for `add` and `edit` are not showing the correct command format under Command Summary section. 

The `add` command format should be: `add n/NAME p/PHONE_NUMBER e/EMAIL m/MAJOR [t/TAG]…​`
The `edit` command format should be: `edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [m/MAJOR] [s/STAR] [b/BOLT] [t/TAG]…​`

Screenshot below shows the incorrect command format for `add` and `edit`
![Screenshot 2024-04-05 at 5.59.48 PM.png](https://raw.githubusercontent.com/choowengyan/ped/main/files/09278180-5a00-4a61-865e-f7737a54a505.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: choowengyan/ped#9

**Comment by chiaryan** [comment] 2024-04-08 03:06
Duplicate of john #117

**Closed as completed by chiaryan** 2024-04-08 03:06 UTC
Labels: ped-fix-ug
