### ISSUE TITLE
[PE-D][Tester E] `add` command under glossary outdated

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-4/tp#125] opened 2024-04-05 19:50 UTC
`add` and `edit` command under glossary still uses `AddressBook` commands.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: darkvoid32/ped#7

**Comment by chiaryan** [comment] 2024-04-08 04:18
Duplicate of #117

**Closed as completed by chiaryan** 2024-04-08 04:18 UTC
Labels: ped-fix-ug
